### Inlämningsuppgift_2_Yunus_Abubakar

## PART 1

In [1]:
import numpy as np #import numpy
import random #import random

In [2]:
'''
1. Construct an array with 10 columns and 5 rows of float numbers. No number
must be same
'''
np.random.seed(0) #initialize pseudorandom number generator
array1 = np.random.rand(50).reshape(5,10)
array1

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
        0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
        0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ,
        0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
        0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077]])

In [3]:
'''
2. Construct another new array with 10 columns and 7 rows of float numbers.
It should not contain the same number as the one from the previous task.
'''
np.random.seed(1) #initialize pseudorandom number generator
array2 = np.random.rand(70).reshape(7,10)
array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02, 6.70467510e-01, 4.17304802e-01, 5.58689828e-01,
        1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02,
        1.69830420e-01, 8.78142503e-01],
       [9.83468338e-02, 4.21107625e-01, 9.57889530e-01, 5.33165285e-01,
        6.91877114e-01, 3.15515631e-01, 6.86500928e-01, 8.34625672e-01,
        1.82882773e-02, 7.50144315e-01],
       [9.88861089e-01, 7.48165654e-01, 2.80443992e-01, 7.89279328e-01,
        1.03226007e-01, 4.47893526e-01, 9.08595503e-01, 2.93614148e-01,
        2.87775339e-01, 1.30028572e-01],
       [1.93669579e-02, 6.78835533e-01, 2.11628116e-01, 2.65546659e-01,
   

In [4]:
'''
3. Redo the two arrays from the previous tasks so that they have 5 columns,
with as many extra rows as needed.
'''
array3 = array1.reshape(-1,5)
print(f'Array1 is now being reshaped into\n {array3}')

print()

array4 = array2.reshape(-1,5)
print(f'Array2 is now being reshaped into\n {array4}')

Array1 is now being reshaped into
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]

Array2 is now being reshaped into
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01]
 [9.23385948e-02 1.86260211e-01 3.45560727e-01 3.96767474e-01
  5.38816734e-01]
 [4.19194514e-01 6.85219500e-01 2.04452250e-01 8.78117436e-01
  2.73875932e-02]
 [6.70467510e-01 4.17304802e-01 5.58689828e-01 1.40386939e-01
  1.98101489e-01]
 [8.00744569e-01 9.68261576e

In [5]:
'''
4. Now take the two arrays from the previous tasks and stack them into one
array that still has five columns.
'''
stacked_array = np.vstack((array3, array4))
stacked_array

array([[5.48813504e-01, 7.15189366e-01, 6.02763376e-01, 5.44883183e-01,
        4.23654799e-01],
       [6.45894113e-01, 4.37587211e-01, 8.91773001e-01, 9.63662761e-01,
        3.83441519e-01],
       [7.91725038e-01, 5.28894920e-01, 5.68044561e-01, 9.25596638e-01,
        7.10360582e-02],
       [8.71292997e-02, 2.02183974e-02, 8.32619846e-01, 7.78156751e-01,
        8.70012148e-01],
       [9.78618342e-01, 7.99158564e-01, 4.61479362e-01, 7.80529176e-01,
        1.18274426e-01],
       [6.39921021e-01, 1.43353287e-01, 9.44668917e-01, 5.21848322e-01,
        4.14661940e-01],
       [2.64555612e-01, 7.74233689e-01, 4.56150332e-01, 5.68433949e-01,
        1.87898004e-02],
       [6.17635497e-01, 6.12095723e-01, 6.16933997e-01, 9.43748079e-01,
        6.81820299e-01],
       [3.59507901e-01, 4.37031954e-01, 6.97631196e-01, 6.02254716e-02,
        6.66766715e-01],
       [6.70637870e-01, 2.10382561e-01, 1.28926298e-01, 3.15428351e-01,
        3.63710771e-01],
       [4.17022005e-01, 7.2032

In [6]:
'''
5. Change the order of the columns so that they come in the order column5,
column3, column4, column1, column2
'''
rearranged_array = stacked_array[:, [4,2,3,0,1]]
rearranged_array

array([[4.23654799e-01, 6.02763376e-01, 5.44883183e-01, 5.48813504e-01,
        7.15189366e-01],
       [3.83441519e-01, 8.91773001e-01, 9.63662761e-01, 6.45894113e-01,
        4.37587211e-01],
       [7.10360582e-02, 5.68044561e-01, 9.25596638e-01, 7.91725038e-01,
        5.28894920e-01],
       [8.70012148e-01, 8.32619846e-01, 7.78156751e-01, 8.71292997e-02,
        2.02183974e-02],
       [1.18274426e-01, 4.61479362e-01, 7.80529176e-01, 9.78618342e-01,
        7.99158564e-01],
       [4.14661940e-01, 9.44668917e-01, 5.21848322e-01, 6.39921021e-01,
        1.43353287e-01],
       [1.87898004e-02, 4.56150332e-01, 5.68433949e-01, 2.64555612e-01,
        7.74233689e-01],
       [6.81820299e-01, 6.16933997e-01, 9.43748079e-01, 6.17635497e-01,
        6.12095723e-01],
       [6.66766715e-01, 6.97631196e-01, 6.02254716e-02, 3.59507901e-01,
        4.37031954e-01],
       [3.63710771e-01, 1.28926298e-01, 3.15428351e-01, 6.70637870e-01,
        2.10382561e-01],
       [1.46755891e-01, 1.1437

## PART 2

In [7]:
import pandas as pd #import pandas
assults = pd.read_csv('assults.csv') #load data

In [8]:
assults.head() #view first 5 rows of the dataset

Index  Area_unit_2013_code             Area_unit_2013_label  \
0      1               514102            Auckland Central West   
1      2               573101  Willis Street-Cambridge Terrace   
2      3               529700                 Hamilton Central   
3      4               514103            Auckland Central East   
4      5               591500                 Cathedral Square   

   Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                550                      15900   
1                                447                       8300   
2                                380                       3170   
3                                375                      13250   
4                                305                        570   

  Rate_per_10000_population  Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
0                       346                         6.6                     4   
1                       539                        10.3                    20   
2                     1,199                        22.9                     6   
3                       283                         5.4                     4   
4                     5,351                       102.3                    22   

   Urban_area_2013_label  Urban_area_type  \
0  Central Auckland Zone  Main urban area   
1        Wellington Zone  Main urban area   
2          Hamilton Zone  Main urban area   
3  Central Auckland Zone  Main urban area   
4           Christchurch  Main urban area   

   Territorial_authority_area_2013_code Territorial_authority_area_2013_label  \
0                                    76                              Auckland   
1                                    47                       Wellington City   
2                                    16                         Hamilton City   
3                                    76                              Auckland   
4                                    60                     Christchurch City   

   Region_2013_code  Region_2013_label  
0                 2    Auckland Region  
1                 9  Wellington Region  
2                 3     Waikato Region  
3                 2    Auckland Region  
4                13  Canterbury Region

In [9]:
'''
1. How many regions are included in the data? The regions can be found under "Region_2013_label".
'''
assults["Region_2013_label"].nunique()

17

In [10]:
''' 
2. List the regions in alphabetical order.
'''
sorted(assults["Region_2013_label"].unique())

['Area Outside Region',
 'Auckland Region',
 'Bay of Plenty Region',
 'Canterbury Region',
 'Gisborne Region',
 "Hawke's Bay Region",
 'Manawatu-Wanganui Region',
 'Marlborough Region',
 'Nelson Region',
 'Northland Region',
 'Otago Region',
 'Southland Region',
 'Taranaki Region',
 'Tasman Region',
 'Waikato Region',
 'Wellington Region',
 'West Coast Region']

In [11]:
'''
3. What was the population of each region in the middle of the year 2015? Use Pandas to display
'''
region_population = assults.groupby("Region_2013_label")["Population_mid_point_2015"].sum()
region_population

Region_2013_label
Area Outside Region             610
Auckland Region             1569890
Bay of Plenty Region         287130
Canterbury Region            586310
Gisborne Region               47370
Hawke's Bay Region           160010
Manawatu-Wanganui Region     234460
Marlborough Region            45340
Nelson Region                 49940
Northland Region             168320
Otago Region                 215030
Southland Region              97190
Taranaki Region              115760
Tasman Region                 49500
Waikato Region               439000
Wellington Region            496890
West Coast Region             32700
Name: Population_mid_point_2015, dtype: int64

In [12]:
'''
4. How many crimes were committed in each region in 2015? You will find the crimes in the 
column "Victimizations_calendar_year_2015
'''
assults.groupby("Region_2013_label")["Victimisations_calendar_year_2015"].sum()

Region_2013_label
Area Outside Region            0
Auckland Region             8010
Bay of Plenty Region        1751
Canterbury Region           2942
Gisborne Region              436
Hawke's Bay Region          1068
Manawatu-Wanganui Region    1270
Marlborough Region           209
Nelson Region                357
Northland Region             905
Otago Region                1142
Southland Region             381
Taranaki Region              493
Tasman Region                161
Waikato Region              2330
Wellington Region           2459
West Coast Region            121
Name: Victimisations_calendar_year_2015, dtype: int64

In [13]:
'''
5. Show the 10 areas with the highest number of assaults. Areas are "Area_unit_2013_label".
'''
assults.groupby("Area_unit_2013_label")["Victimisations_calendar_year_2015"].sum().sort_values(ascending = False).head(10)

Area_unit_2013_label
Auckland Central West              550
Willis Street-Cambridge Terrace    447
Hamilton Central                   380
Auckland Central East              375
Cathedral Square                   305
Auckland Harbourside               253
Manukau Central                    192
Palmerston North Central           190
Kuirau                             168
Tauranga Central                   167
Name: Victimisations_calendar_year_2015, dtype: int64

In [14]:
'''
6. Add a column to the dataframe that shows the % number of assaults in the area compared to population in the area. 
Each row is an area.
'''
assults_copy = assults.copy()
assults_copy["percentage_assult"] = (assults_copy["Victimisations_calendar_year_2015"] / assults_copy["Population_mid_point_2015"] * 100)

In [15]:
assults_copy.head()

Index  Area_unit_2013_code             Area_unit_2013_label  \
0      1               514102            Auckland Central West   
1      2               573101  Willis Street-Cambridge Terrace   
2      3               529700                 Hamilton Central   
3      4               514103            Auckland Central East   
4      5               591500                 Cathedral Square   

   Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                550                      15900   
1                                447                       8300   
2                                380                       3170   
3                                375                      13250   
4                                305                        570   

  Rate_per_10000_population  Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
0                       346                         6.6                     4   
1                       539                        10.3                    20   
2                     1,199                        22.9                     6   
3                       283                         5.4                     4   
4                     5,351                       102.3                    22   

   Urban_area_2013_label  Urban_area_type  \
0  Central Auckland Zone  Main urban area   
1        Wellington Zone  Main urban area   
2          Hamilton Zone  Main urban area   
3  Central Auckland Zone  Main urban area   
4           Christchurch  Main urban area   

   Territorial_authority_area_2013_code Territorial_authority_area_2013_label  \
0                                    76                              Auckland   
1                                    47                       Wellington City   
2                                    16                         Hamilton City   
3                                    76                              Auckland   
4                                    60                     Christchurch City   

   Region_2013_code  Region_2013_label  percentage_assult  
0                 2    Auckland Region           3.459119  
1                 9  Wellington Region           5.385542  
2                 3     Waikato Region          11.987382  
3                 2    Auckland Region           2.830189  
4                13  Canterbury Region          53.508772

In [16]:
'''
7. Create a new dataframe that contains the number of areas (Area_unit_2013_label) that exist 
of the different types of urban area (Urban_area_2013_label).
'''
urban_area = assults.groupby("Urban_area_2013_label")["Area_unit_2013_label"].count()
df_urban_area = pd.DataFrame(urban_area)
df_urban_area = df_urban_area.reset_index()
new_dataframe = df_urban_area.rename(columns = {"Area_unit_2013_label": "Number_of_areas"})
new_dataframe


Urban_area_2013_label  Number_of_areas
0               Alexandra                1
1                Amberley                1
2               Arrowtown                1
3               Ashburton               11
4               Balclutha                1
..                    ...              ...
145             Whangarei               29
146             Whitianga                1
147                Winton                1
148               Woodend                3
149             Woodville                1

[150 rows x 2 columns]

In [17]:
'''
8. Find how many areas (each row is an area) had population but no raids.

'''
pop_but_no_raid = assults[(assults["Victimisations_calendar_year_2015"]==0) & (assults["Population_mid_point_2015"] > 0)]
pop_but_no_raid

Index  Area_unit_2013_code               Area_unit_2013_label  \
1729   1730               626100                Inlet-Milford Sound   
1730   1731               623900                    Inlet-Ligar Bay   
1731   1732               625800                Inlet-Otago Harbour   
1732   1733               619301  Inlets-Thames-Coromandel District   
1733   1734               612901                          Fiordland   
...     ...                  ...                                ...   
2015   2016               506653                          Riverhead   
2016   2017               610601                           Grasmere   
2017   2018               536513                     Bethlehem East   
2018   2019               574302                          Te Kainga   
2019   2020               527007                      Horsham Downs   

      Victimisations_calendar_year_2015  Population_mid_point_2015  \
1729                                  0                         10   
1730                                  0                         10   
1731                                  0                         10   
1732                                  0                         10   
1733                                  0                         10   
...                                 ...                        ...   
2015                                  0                       3510   
2016                                  0                       3590   
2017                                  0                       3590   
2018                                  0                       4020   
2019                                  0                       5440   

     Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
1729                       NaN                         NaN   
1730                       NaN                         NaN   
1731                       NaN                         NaN   
1732                       NaN                         NaN   
1733                       NaN                         NaN   
...                        ...                         ...   
2015                       NaN                         NaN   
2016                       NaN                         NaN   
2017                       NaN                         NaN   
2018                       NaN                         NaN   
2019                       NaN                         NaN   

      Urban_area_2013_code                Urban_area_2013_label  \
1729                   507    Inlet-in TA but not in Urban Area   
1730                   507    Inlet-in TA but not in Urban Area   
1731                   507    Inlet-in TA but not in Urban Area   
1732                   507    Inlet-in TA but not in Urban Area   
1733                   502  Rural (Incl.some Off Shore Islands)   
...                    ...                                  ...   
2015                   502  Rural (Incl.some Off Shore Islands)   
2016                    24                         Invercargill   
2017                     9                             Tauranga   
2018                    20                      Wellington Zone   
2019                     6                        Hamilton Zone   

      Urban_area_type  Territorial_authority_area_2013_code  \
1729       Rural area                                    73   
1730       Rural area                                    51   
1731       Rural area                                    71   
1732       Rural area                                    11   
1733       Rural area                                    73   
...               ...                                   ...   
2015       Rural area                                    76   
2016  Main urban area                                    75   
2017  Main urban area                                    23   
2018  Main urban area                                    47   
2019  Main urban area                                    16   

     

In [18]:
'''
Compare the total population in these with the total population in their region (Region_2013_label).
'''
total_no_raid_population = pop_but_no_raid["Population_mid_point_2015"].sum() #total population
region_data = assults.groupby("Region_2013_label")["Population_mid_point_2015"].sum()

region_df = pd.DataFrame (region_data)
region_df.reset_index(inplace = True)
region_df["total_no_raid_population"] = total_no_raid_population
region_df["region_pop_to_no_raid__total_pop"] = (total_no_raid_population/region_df["Population_mid_point_2015"])

region_df

Region_2013_label  Population_mid_point_2015  \
0        Area Outside Region                        610   
1            Auckland Region                    1569890   
2       Bay of Plenty Region                     287130   
3          Canterbury Region                     586310   
4            Gisborne Region                      47370   
5         Hawke's Bay Region                     160010   
6   Manawatu-Wanganui Region                     234460   
7         Marlborough Region                      45340   
8              Nelson Region                      49940   
9           Northland Region                     168320   
10              Otago Region                     215030   
11          Southland Region                      97190   
12           Taranaki Region                     115760   
13             Tasman Region                      49500   
14            Waikato Region                     439000   
15         Wellington Region                     496890   
16         West Coast Region                      32700   

    total_no_raid_population  region_pop_to_no_raid__total_pop  
0                     212780                        348.819672  
1                     212780                          0.135538  
2                     212780                          0.741058  
3                     212780                          0.362914  
4                     212780                          4.491872  
5                     212780                          1.329792  
6                     212780                          0.907532  
7                     212780                          4.692986  
8                     212780                          4.260713  
9                     212780                          1.264140  
10                    212780                          0.989536  
11                    212780                          2.189320  
12                    212780                          1.838113  
13                    212780                          4.298586  
14                    212780                          0.484692  
15                    212780                          0.428224  
16                    212780                          6.507034

In [19]:
'''
9. Count per column how many rows there are that do not contain any data
'''
assults.isnull().sum()

Index                                      0
Area_unit_2013_code                        0
Area_unit_2013_label                       0
Victimisations_calendar_year_2015          0
Population_mid_point_2015                  0
Rate_per_10000_population                417
Rate_ratio_NZ_average_rate               417
Urban_area_2013_code                       0
Urban_area_2013_label                      0
Urban_area_type                            0
Territorial_authority_area_2013_code       0
Territorial_authority_area_2013_label      0
Region_2013_code                           0
Region_2013_label                          0
dtype: int64

In [20]:
'''
10. Create a new dataframe with 10 rows. It contains the 10 rows with the
lowest number of assaults per inhabitant (Rate_per_10000_population), but more than 5000 
inhabitants
'''

pop_500_above = assults[assults["Population_mid_point_2015"] > 5000]
pop_500_abovee = pop_500_above.dropna(subset = ["Rate_per_10000_population"])
pop_500_abovee = pop_500_abovee.astype({'Rate_per_10000_population': 'int'})
final = pop_500_abovee.sort_values("Rate_per_10000_population", ignore_index = True).head(10);
final

Index  Area_unit_2013_code Area_unit_2013_label  \
0   1613               516302     Meadowbank South   
1   1612               507300          Murrays Bay   
2   1393               527131    Tamahere-Tauwhare   
3   1394               514600       Avondale South   
4   1392               506903               Torbay   
5   1391               521502           Cockle Bay   
6   1390               581260            Witherlea   
7   1238               537000                Matua   
8   1237               508704           Northcross   
9   1236               588500     Bishopdale North   

   Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                  1                       5560   
1                                  1                       5150   
2                                  2                       6110   
3                                  2                       6110   
4                                  2                       5330   
5                                  2                       5190   
6                                  2                       5090   
7                                  3                       5440   
8                                  3                       5060   
9                                  3                       5010   

   Rate_per_10000_population  Rate_ratio_NZ_average_rate  \
0                          2                         0.0   
1                          2                         0.0   
2                          3                         0.1   
3                          3                         0.1   
4                          4                         0.1   
5                          4                         0.1   
6                          4                         0.1   
7                          6                         0.1   
8                          6                         0.1   
9                          6                         0.1   

   Urban_area_2013_code   Urban_area_2013_label  Urban_area_type  \
0                     4   Central Auckland Zone  Main urban area   
1                     2  Northern Auckland Zone  Main urban area   
2                     6           Hamilton Zone  Main urban area   
3                     4   Central Auckland Zone  Main urban area   
4                     2  Northern Auckland Zone  Main urban area   
5                     5  Southern Auckland Zone  Main urban area   
6                    26                Blenheim  Main urban area   
7                     9                Tauranga  Main urban area   
8                     2  Northern Auckland Zone  Main urban area   
9                    22            Christchurch  Main urban area   

   Territorial_authority_area_2013_code Territorial_authority_area_2013_label  \
0                                    76                              Auckland   
1                                    76                              Auckland   
2                                    13                      Waikato District   
3                                    76                              Auckland   
4                                    76                              Auckland   
5                                    76                              Auckland   
6                                    53                  Marlborough District   
7                                    23                         Tauranga City   
8                                    76                              Auckland   
9                                    60                     Christchurch City   

   Region_2013_code     Region_2013_label  
0                 2       Auckland Region  
1                 2       Auckland Region  
2                 3        Waikato Region  
3                 2       Auckland Region  
4                 2       Auckland Region  
5                 2       Auckland Region  
6                18    Marlborough Region  
7               

In [21]:
'''
11. Create a new dataframe "regions" that contains composite data per region (Region_2013_label). 
Add a new column containing "Rate_per_10000_population" fixed for the entire region.
'''
regions = assults.groupby("Region_2013_label").sum()
regions.reset_index(inplace=True)
regions
regions["Rate_per_10000_population"] = (regions["Victimisations_calendar_year_2015"]/regions["Population_mid_point_2015"] * 1000)
regions

Region_2013_label   Index  Area_unit_2013_code  \
0        Area Outside Region   31979             12115406   
1            Auckland Region  351263            228136920   
2       Bay of Plenty Region  116270             69921421   
3          Canterbury Region  263734            152971702   
4            Gisborne Region   18953             13134931   
5         Hawke's Bay Region   80181             46166145   
6   Manawatu-Wanganui Region  128256             72064146   
7         Marlborough Region   31022             15140741   
8              Nelson Region   31980             18146617   
9           Northland Region   96901             49951297   
10              Otago Region  156828             79941938   
11          Southland Region  101248             48378906   
12           Taranaki Region   75287             36602672   
13             Tasman Region   36562             17552636   
14            Waikato Region  214201            112175975   
15         Wellington Region  221263            121963800   
16         West Coast Region   85282             33421322   

    Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   0                        610   
1                                8010                    1569890   
2                                1751                     287130   
3                                2942                     586310   
4                                 436                      47370   
5                                1068                     160010   
6                                1270                     234460   
7                                 209                      45340   
8                                 357                      49940   
9                                 905                     168320   
10                               1142                     215030   
11                                381                      97190   
12                                493                     115760   
13                                161                      49500   
14                               2330                     439000   
15                               2459                     496890   
16                                121                      32700   

    Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
0                          0.0                  9637   
1                        670.7                 36094   
2                        178.1                 25589   
3                        326.7                 48421   
4                         32.7                  5667   
5                        125.3                 14972   
6                        166.3                 28318   
7                         29.5                  7359   
8                         71.3                  2593   
9                        217.7                 31142   
10                       142.2                 30192   
11                        64.7                 26262   
12                        67.0                 15648   
13                        13.8                 10143   
14                       249.9                 48898   
15                       278.4                 19319   
16                        28.9                 24584   

    Territorial_authority_area_2013_code  Region_2013_code  \
0                                  17117              1881   
1                                  33212               874   
2                                   7927               516   
3                                  17572              3354   
4                                   1643               120   
5                                   5451               504   
6                                   6894              1032   
7                                   2324               468   
8                                   2559               527   
9                                   3158                97

In [22]:
'''
12. Add a new column to the dataframe with the regions showing in % how many of all 
assaults that takes place in that region.
'''
total_assults = sum(regions["Victimisations_calendar_year_2015"])
regions["percentage_assults"] = (regions["Victimisations_calendar_year_2015"]/total_assults * 100)
regions

Region_2013_label   Index  Area_unit_2013_code  \
0        Area Outside Region   31979             12115406   
1            Auckland Region  351263            228136920   
2       Bay of Plenty Region  116270             69921421   
3          Canterbury Region  263734            152971702   
4            Gisborne Region   18953             13134931   
5         Hawke's Bay Region   80181             46166145   
6   Manawatu-Wanganui Region  128256             72064146   
7         Marlborough Region   31022             15140741   
8              Nelson Region   31980             18146617   
9           Northland Region   96901             49951297   
10              Otago Region  156828             79941938   
11          Southland Region  101248             48378906   
12           Taranaki Region   75287             36602672   
13             Tasman Region   36562             17552636   
14            Waikato Region  214201            112175975   
15         Wellington Region  221263            121963800   
16         West Coast Region   85282             33421322   

    Victimisations_calendar_year_2015  Population_mid_point_2015  \
0                                   0                        610   
1                                8010                    1569890   
2                                1751                     287130   
3                                2942                     586310   
4                                 436                      47370   
5                                1068                     160010   
6                                1270                     234460   
7                                 209                      45340   
8                                 357                      49940   
9                                 905                     168320   
10                               1142                     215030   
11                                381                      97190   
12                                493                     115760   
13                                161                      49500   
14                               2330                     439000   
15                               2459                     496890   
16                                121                      32700   

    Rate_ratio_NZ_average_rate  Urban_area_2013_code  \
0                          0.0                  9637   
1                        670.7                 36094   
2                        178.1                 25589   
3                        326.7                 48421   
4                         32.7                  5667   
5                        125.3                 14972   
6                        166.3                 28318   
7                         29.5                  7359   
8                         71.3                  2593   
9                        217.7                 31142   
10                       142.2                 30192   
11                        64.7                 26262   
12                        67.0                 15648   
13                        13.8                 10143   
14                       249.9                 48898   
15                       278.4                 19319   
16                        28.9                 24584   

    Territorial_authority_area_2013_code  Region_2013_code  \
0                                  17117              1881   
1                                  33212               874   
2                                   7927               516   
3                                  17572              3354   
4                                   1643               120   
5                                   5451               504   
6                                   6894              1032   
7                                   2324               468   
8                                   2559               527   
9                                   3158                97